# Getting Started {#index}

Welcome to the SyRF User Guide. This guide is designed to help you use SyRF. If you require general guidance on systematic review or meta-analysis, or have never conducted a systematic review before, please read the [Systematic Review Wiki](https://www.camarades.de/) created by CAMARADES Berlin.


## Glossary
### Project
Each project is specific to your systematic review and meta-analysis. Upload your deduplicated studies and add stages to screen and annotate your data.

#### Public project
A project that can be seen by anyone with a SyRF account. Other users can request to join a public project with your approval.

#### Private project
A project that is not visible to other SyRF users unless they have requested and have been granted permission to join the project.

### Protocol
A structured description of what you set out to do in your systematic review and meta-analysis, which should be finalised before you start your systematic review. We recommend that this is published or shared publicly with [PROSPERO](https://www.crd.york.ac.uk/prospero/).

### Screening
Screening refers to making a decision whether to include or exclude a study retrieved in your systematic search based on the inclusion/exclusion criteria defined in your protocol. Screening is described in more detail in

SECTION 9.
<!-- link -->

### Annotation
You may want to annotate your studies by labelling or extracting relevant information from them. This part of a systematic review project is fairly flexible and therefore you can define your own annotation questions. Annotation questions should address all questions you want to ask as specified in your protocol. You can choose at which stage of the project you want to answer specific annotation questions. This is described in more detail in 

SECTION 10.
<!-- link -->

### Data extraction
Where you extract data from graphs or tables in the form of means/medians and corresponding error.

### Experiment
An experiment refers to any grouping of cohorts where an experiment is carried out at the same time and any of them can be compared with each other.

### Cohort
A cohort refers to a group of animals - same species, strain, source, co-morbidities (if applicable) - which all receive the same procedure and treatments and can be compared to other cohorts. For example, an experiment may involve the following cohorts: 

Example Experiment 1:

* Cohort 1: Treatment
* Cohort 2: Sham
* Cohort 3: Control

Example Experiment 2:

* Cohort 1: Control
* Cohort 2: Treatment 1
* Cohort 3: Treatment 2

Cohorts are created in SyRF projects by combining disease models and treatment details. This is described further in

SECTION 10.
<!-- link -->

<< ADD FLOWCHART DIAGRAM >>