# Project Navigation {#nagivation}

## Project details
You can see an overview of the project on the Project Details page. 

In the centre of the page, you will see a screening stage has already been added with the inclusion and exclusion critiera that was added by the Project Administrator during project creation. Click the 'Review' button to enter a stage. If you are a Project Administaton, you will be able to add new stages there too. 

On rhe right hand side of the Project Overview page you can see:

* Contact - the contact email of the project administator
* Protocol url - a link to where the systematic review protocol has been published
* Keywords - any keywords assigned to the project
* Systematic searches - details of studies added to the project
* Project visability - either public or private
* Creation date: the date the project was made
* Members - a list of members on the project

Project details can be edited in the settings by clicking on the cog icons next to each heading.

<< SCREENSHOT OF PROJECT DETAILS PAGE >>

## Studies
You can see the details of all the studiesyou have uploaded to SyRF in the studies tab. To learn how to upload studies or systematic searches, please go to

SECTION 7

<< SCREENSHOT OF STUDIES PAGE >>

## Stages
You can start screening or annotating in a stage by clicking on the stage name and then 'Review'. Note that if the Project Administator has not uploaded any systematic searches, you will not be able to under a stage.

<< SCREENSHOT OF STAGES PAGE >>

## Project settings
Only Project Administators are able to edit project settings.

### General settings
In the geberal project settings, Project Administators can edit:

* Project name
* Project description
* Project visability
* Contact email
* Protocol Url
* Keywords

<< SCREENSHOT OF GENERAL SETTINGS>>

#### Deleting projects
Projects can be deleted from the general settings. Please know that data from deleted projects cannot be recovered.

### Members & groups
Project Administators can change user roles in the members & groups settings page. To make a user a Project Administator, click the checkbox next to their name. Uncheck the box to make them a Reviewer. Canges are saved automatically.

<< SCREENSHOT OF MEMBERS & GROUPS PAGE>>

### Systematic searches
Project Administrators can view the systematic searches that have previously been uploaded, or upload new systematic searches on this page. For more information, go to

SECTION 7

<< SCREENSHOT OF SYSTEMATIC SEARCHES PAGE >>

### Question design
Project Administrators can add and delete annotation questions in their project on this page. These questions can be then assigned to annotation stages. For more information, go to

SECTION 10

<< SCREENSHOT OF QUESTION DESIGN PAGE >>

### Stage settings
In the stage settings, Project Administrators can add and edit stages.

You can decide which elements to add to your stage, e.g. screening, annotation and/or data extraction. If you choose both screening and annotation, you will be asked to choose a study selection mode.

<< SCREENSHOT OF STUDY SELECTION SETTINGS>>

#### Annotation question selection
Project Administators can select which questions they have created in the Question Design settings page to add to each stage. Click the 'Edit project questions' button to return to the question design page.